// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DustBusters",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "DustBusters",
            targets: ["AppModule"],
            bundleIdentifier: "com.Lets.DustBusters",
            teamIdentifier: "CZH2CMCGCZ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "Need to use camera for DustBusters!")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resource")
            ]
        )
    ]
)